
version: 2

sources:
  - name: public
    tables:
      - name: jaffle_shop_orders
      - name: jaffle_shop_customers

models:
  - name: model_raw
    description: "Orders Raw Data"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: user_id
      - name: order_date
      - name: status

  - name: model_staging
    description: "Orders Staging Data"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
