
version: 2

sources:
  - name: public
    tables:
      - name: jaffle_shop_orders
      - name: jaffle_shop_customers

models:
  - name: staging_orders_completed
    description: "Completed Orders"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: user_id
      - name: order_date

  - name: staging_customers_name
    description: "Customers Full Name"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: full_name

  - name: datamart_customer_orders
    description: "No. of Orders per Customer"
    columns:
      - name: id
        quote: true
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: full_name
      - name: total_orders
