
version: 2

sources:
  - name: raw
    database: postgres
    schema: public
    tables:
      - name: orders
        identifier: jaffle_shop_orders
      - name: customers
        identifier: jaffle_shop_customers

models:
  - name: stg_orders
    description: "Completed Orders"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: user_id
      - name: order_date

  - name: stg_customers
    description: "Customers Full Name"
    columns:
      - name: customer_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: full_name

  - name: mart_orders
    description: "No. of Orders per Customer"
    columns:
      - name: customer_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: full_name
      - name: total_orders
